apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\jonhy\Downloads\kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: gateway
